# TERMINAL
set-option -sa terminal-overrides ",xterm*:Tc"

# LEADER KEY
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# CLEAR
bind    C-k send-keys C-l \; clear-history

# WINDOWS
bind M-Left  new-window -b
bind M-Right new-window -a
bind M-Up    new-window
bind M-Down  new-window -t :=0
## Alt+Arrow L&R to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window
## Window naming
set-option -g allow-rename off


# PANES
## Split
bind S-Right split-window -h    -c "#{pane_current_path}"
bind S-Left  split-window -h -b -c "#{pane_current_path}"
bind S-Up    split-window -v -b -c "#{pane_current_path}"
bind S-Down  split-window -v    -c "#{pane_current_path}"
## Shift+Arrow to select panes
bind -n S-Left  select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up    select-pane -U
bind -n S-Down  select-pane -D
## Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# MOUSE
set -g mouse on

# CLIPBOARD
set-option -g set-clipboard on

# CONFIG
## Reload config
bind S-r source-file ~/.config/tmux/tmux.conf

# PLUGINS
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$TMUX_PLUGIN_MANAGER_PATH"

## List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

## Themes
### https://github.com/maxpetretta/tmux-monokai-pro
set -g @plugin 'maxpetretta/tmux-monokai-pro'

## Available plugins:
# - battery
# - cpu-usage
# - git
# - gpu-usage
# - ram-usage
# - tmux-ram-usage
# - network
# - network-bandwidth
# - network-ping
# - attached-clients
# - network-vpn
# - weather
# - time
# - kubernetes-context
# - synchronize-panes

# set -g @monokai-plugins "cpu-usage ram-usage battery"
set -g @monokai-plugins "battery"
set -g @monokai-battery-label "BAT"
set -g @monokai-battery-label "󰂈"
set -g @monokai-cpu-usage-label "CPU"
set -g @monokai-cpu-usage-label ""
set -g @monokai-ram-usage-label "RAM"
set -g @monokai-ram-usage-label ""

# Available colors:
# - white
# - gray
# - dark_gray
# - light_purple
# - dark_purple
# - cyan
# - green
# - orange
# - red
# - pink
# - yellow
# set -g @monokai-[plugin-name]-colors "[background] [foreground]"

## Colors
set -g @monokai-battery-colors "gray white"

## Enable powerline symbols
set -g @monokai-show-powerline true
set -g @monokai-show-edge-icons true

set -g @monokai-show-left-sep 
set -g @monokai-show-right-sep 
set -g @monokai-transparent-powerline-bg true
# set -g @monokai-inverse-divider 


## Enable window flags
set -g @monokai-show-flags false

## Switch the left smiley icon
## it can accept `session`, `smiley`, `window`, or any character.
set -g @monokai-show-left-icon 'session'
# set -g @monokai-show-left-icon 🐼
# set -g @monokai-left-pad false

## Enable high contrast pane border
set -g @monokai-border-contrast false

## Hide empty plugins
set -g @monokai-show-empty-plugins false

## Ping
set -g @monokai-ping-server "google.com"
set -g @monokai-ping-rate 5

## Git
set -g @monokai-git-disable-status true
## Set symbol to use for when branch is up to date with HEAD
## default is ✓. Avoid using non unicode characters that bash uses like $, * and !
set -g @monokai-git-show-current-symbol ✓
## Set symbol to use for when branch diverges from HEAD
## default is unicode !. Avoid bash special characters
set -g @monokai-git-show-diff-symbol !
set -g @monokai-synchronize-panes-label "Sync"

# run '/opt/homebrew/opt/tpm/share/tpm/tpm'
run-shell "/opt/homebrew/opt/tpm/share/tpm/tpm"

